apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: j12t-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: grafana-data
          mountPath: /var/lib/grafana
      volumes:
      - name: grafana-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: j12t-monitoring
spec:
  selector:
    app: grafana
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: j12t-monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'worker-0'
        static_configs:
          - targets: ['simpleapp-0.simpleapp-server.j12t.svc.cluster.local:9126']
      - job_name: 'worker-1'
        static_configs:
          - targets: ['simpleapp-1.simpleapp-server.j12t.svc.cluster.local:9126']
      - job_name: 'nginx-0'
        static_configs:
          - targets: ['simpleapp-nginx-0.simpleapp-nginx.j12t.svc.cluster.local:9126']
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus
  namespace: j12t-monitoring
spec:
  selector:
    matchLabels:
      app: prometheus # has to match .spec.template.metadata.labels
  serviceName: prometheus # has to match headless Service metadata.name
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: prometheus # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: prometheus
        image: prom/prometheus:latest
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: prometheus-config-volume
          mountPath: /etc/prometheus
      volumes:
      - name: prometheus-config-volume
        configMap:
          name: prometheus-config
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: j12t-monitoring
spec:
  type: NodePort
  selector:
    app: prometheus
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      name: prometheus