---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: simpleapp-set1
spec:
  serviceName: "simpleapp-set1"
  replicas: 1
  selector:
    matchLabels:
      app: simpleapp-set1
  template:
    metadata:
      labels:
        app: simpleapp-set1
    spec:
      containers:
      - name: simpleapp-container
        image: jerapiblannett/loadbalancersimpleappcsharp:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "1Gi"
            cpu: "0.5"
          limits:
            memory: "1Gi"
            cpu: "0.5"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: simpleapp-set2
spec:
  serviceName: "simpleapp-set2"
  replicas: 1
  selector:
    matchLabels:
      app: simpleapp-set2
  template:
    metadata:
      labels:
        app: simpleapp-set2
    spec:
      containers:
      - name: simpleapp-container
        image: jerapiblannett/loadbalancersimpleappcsharp:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "2Gi"
            cpu: "1"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: simpleapp-set3
spec:
  serviceName: "simpleapp-set3"
  replicas: 1
  selector:
    matchLabels:
      app: simpleapp-set3
  template:
    metadata:
      labels:
        app: simpleapp-set3
    spec:
      containers:
      - name: simpleapp-container
        image: jerapiblannett/loadbalancersimpleappcsharp:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "4Gi"
            cpu: "2"
          limits:
            memory: "4Gi"
            cpu: "2"
---
apiVersion: v1
kind: Service
metadata:
  name: simpleapp-set1-service
  labels:
    app: simpleapp-set1
spec:
  selector:
    app: simpleapp-set1
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: simpleapp-set2-service
  labels:
    app: simpleapp-set2
spec:
  selector:
    app: simpleapp-set2
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: simpleapp-set3-service
  labels:
    app: simpleapp-set3
spec:
  selector:
    app: simpleapp-set3
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
